/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.makekml;

import javax.swing.*;

/**
 *
 * @author user
 */
public class MetkaFrame extends javax.swing.JFrame {

    /**
     * Creates new form MetkaFrame
     */
    public MetkaFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pHarakterZeli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pKtoVupZadachy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pZametka = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        pNZeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pXc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pYc = new javax.swing.JTextField();
        btnZapisat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Метка");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Характер Цели");

        pHarakterZeli.setBackground(new java.awt.Color(204, 255, 204));
        pHarakterZeli.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pHarakterZeli.setForeground(new java.awt.Color(0, 0, 0));
        pHarakterZeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pHarakterZeliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Кто выполнял задачу");

        pKtoVupZadachy.setBackground(new java.awt.Color(204, 255, 204));
        pKtoVupZadachy.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pKtoVupZadachy.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Заметка");

        pZametka.setBackground(new java.awt.Color(204, 255, 204));
        pZametka.setColumns(20);
        pZametka.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pZametka.setForeground(new java.awt.Color(0, 0, 0));
        pZametka.setRows(5);
        jScrollPane1.setViewportView(pZametka);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("№ Цели");

        pNZeli.setBackground(new java.awt.Color(204, 255, 204));
        pNZeli.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pNZeli.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Х = ");

        pXc.setBackground(new java.awt.Color(255, 204, 204));
        pXc.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pXc.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Y = ");

        pYc.setBackground(new java.awt.Color(255, 204, 204));
        pYc.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pYc.setForeground(new java.awt.Color(51, 51, 51));

        btnZapisat.setBackground(new java.awt.Color(255, 153, 51));
        btnZapisat.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnZapisat.setForeground(new java.awt.Color(0, 0, 0));
        btnZapisat.setText("ЗАПИСАТЬ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74)
                        .addComponent(pHarakterZeli, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pKtoVupZadachy))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(pNZeli, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pXc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pYc)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnZapisat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pHarakterZeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pKtoVupZadachy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pNZeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pXc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(pYc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnZapisat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pHarakterZeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pHarakterZeliActionPerformed
   
        // TODO add your handling code here:
    }//GEN-LAST:event_pHarakterZeliActionPerformed


//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MetkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MetkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MetkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MetkaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MetkaFrame().setVisible(true);
//            }
//        });
//    }

    public void setpKtoVupZadachy(JTextField pKtoVupZadachy) {
        this.pKtoVupZadachy = pKtoVupZadachy;
    }

    public void setpNZeli(JTextField pNZeli) {
        this.pNZeli = pNZeli;
    }

    public void setpXc(JTextField pXc) {
        this.pXc = pXc;
    }

    public void setpYc(JTextField pYc) {
        this.pYc = pYc;
    }

    public void setpZametka(JTextArea pZametka) {
        this.pZametka = pZametka;
    }

    public JButton getBtnZapisat() {
        return btnZapisat;
    }

    public JTextField getpHarakterZeli() {
        return pHarakterZeli;
    }

    public JTextField getpKtoVupZadachy() {
        return pKtoVupZadachy;
    }

    public JTextField getpNZeli() {
        return pNZeli;
    }

    public JTextField getpXc() {
        return pXc;
    }

    public JTextField getpYc() {
        return pYc;
    }

    public JTextArea getpZametka() {
        return pZametka;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZapisat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pHarakterZeli;
    private javax.swing.JTextField pKtoVupZadachy;
    private javax.swing.JTextField pNZeli;
    private javax.swing.JTextField pXc;
    private javax.swing.JTextField pYc;
    private javax.swing.JTextArea pZametka;
    // End of variables declaration//GEN-END:variables
}
